#!/bin/bash

echo
echo "Download GSAP and Plugins"
echo "========================="
echo "https://www.jsdelivr.com/package/npm/gsap"
echo

# Change directory to the script's location
cd "$(dirname "$0")" || exit

echo "Configuring Version and URLs"
echo "----------------------------"
VERSION="3.13.0"
BASE_URL="https://cdn.jsdelivr.net/npm/gsap@${VERSION}/dist"

# Core and Plugins
URL_GSAP="${BASE_URL}/gsap.min.js"
URL_DRAGGABLE="${BASE_URL}/Draggable.min.js"
URL_DRAWSVG="${BASE_URL}/DrawSVGPlugin.min.js"
URL_EASEL="${BASE_URL}/EaselPlugin.min.js"
URL_FLIP="${BASE_URL}/Flip.min.js"
URL_GSDEVTOOLS="${BASE_URL}/GSDevTools.min.js"
URL_INERTIA="${BASE_URL}/InertiaPlugin.min.js"
URL_MOTIONPATHHELPER="${BASE_URL}/MotionPathHelper.min.js"
URL_MOTIONPATH="${BASE_URL}/MotionPathPlugin.min.js"
URL_MORPHSVG="${BASE_URL}/MorphSVGPlugin.min.js"
URL_OBSERVER="${BASE_URL}/Observer.min.js"
URL_PHYSICS2D="${BASE_URL}/Physics2DPlugin.min.js"
URL_PHYSICSPROPS="${BASE_URL}/PhysicsPropsPlugin.min.js"
URL_PIXI="${BASE_URL}/PixiPlugin.min.js"
URL_SCRAMBLETEXT="${BASE_URL}/ScrambleTextPlugin.min.js"
URL_SCROLLTRIGGER="${BASE_URL}/ScrollTrigger.min.js"
URL_SCROLLSMOOTHER="${BASE_URL}/ScrollSmoother.min.js"
URL_SCROLLTO="${BASE_URL}/ScrollToPlugin.min.js"
URL_SPLITTEXT="${BASE_URL}/SplitText.min.js"
URL_TEXTP="${BASE_URL}/TextPlugin.min.js"
URL_EASEPACK="${BASE_URL}/EasePack.min.js"
URL_CUSTOMEASE="${BASE_URL}/CustomEase.min.js"
URL_CUSTOMBOUNCE="${BASE_URL}/CustomBounce.min.js"
URL_CUSTOMWIGGLE="${BASE_URL}/CustomWiggle.min.js"

# License (optional, not versioned on CDN)
URL_LICENSE="https://gsap.com/standard-license"

echo
echo "Configuring Target Directories and Files"
echo "----------------------------------------"
TARGET_WWW_DIR="../wwwroot"
TARGET_JS_DIR="${TARGET_WWW_DIR}/js"
TARGET_LICENSE="${TARGET_WWW_DIR}/LICENSE-gsap.txt"

TARGET_GSAP="${TARGET_JS_DIR}/gsap.min.js"
TARGET_DRAGGABLE="${TARGET_JS_DIR}/Draggable.min.js"
TARGET_DRAWSVG="${TARGET_JS_DIR}/DrawSVGPlugin.min.js"
TARGET_EASEL="${TARGET_JS_DIR}/EaselPlugin.min.js"
TARGET_FLIP="${TARGET_JS_DIR}/Flip.min.js"
TARGET_GSDEVTOOLS="${TARGET_JS_DIR}/GSDevTools.min.js"
TARGET_INERTIA="${TARGET_JS_DIR}/InertiaPlugin.min.js"
TARGET_MOTIONPATHHELPER="${TARGET_JS_DIR}/MotionPathHelper.min.js"
TARGET_MOTIONPATH="${TARGET_JS_DIR}/MotionPathPlugin.min.js"
TARGET_MORPHSVG="${TARGET_JS_DIR}/MorphSVGPlugin.min.js"
TARGET_OBSERVER="${TARGET_JS_DIR}/Observer.min.js"
TARGET_PHYSICS2D="${TARGET_JS_DIR}/Physics2DPlugin.min.js"
TARGET_PHYSICSPROPS="${TARGET_JS_DIR}/PhysicsPropsPlugin.min.js"
TARGET_PIXI="${TARGET_JS_DIR}/PixiPlugin.min.js"
TARGET_SCRAMBLETEXT="${TARGET_JS_DIR}/ScrambleTextPlugin.min.js"
TARGET_SCROLLTRIGGER="${TARGET_JS_DIR}/ScrollTrigger.min.js"
TARGET_SCROLLSMOOTHER="${TARGET_JS_DIR}/ScrollSmoother.min.js"
TARGET_SCROLLTO="${TARGET_JS_DIR}/ScrollToPlugin.min.js"
TARGET_SPLITTEXT="${TARGET_JS_DIR}/SplitText.min.js"
TARGET_TEXTP="${TARGET_JS_DIR}/TextPlugin.min.js"
TARGET_EASEPACK="${TARGET_JS_DIR}/EasePack.min.js"
TARGET_CUSTOMEASE="${TARGET_JS_DIR}/CustomEase.min.js"
TARGET_CUSTOMBOUNCE="${TARGET_JS_DIR}/CustomBounce.min.js"
TARGET_CUSTOMWIGGLE="${TARGET_JS_DIR}/CustomWiggle.min.js"

echo
echo "Creating Directories"
echo "--------------------"
mkdir -p "$TARGET_JS_DIR"

echo
echo "Downloading Files"
echo "-----------------"
curl -o "$TARGET_GSAP" "$URL_GSAP"
curl -o "$TARGET_DRAGGABLE" "$URL_DRAGGABLE"
curl -o "$TARGET_DRAWSVG" "$URL_DRAWSVG"
curl -o "$TARGET_EASEL" "$URL_EASEL"
curl -o "$TARGET_FLIP" "$URL_FLIP"
curl -o "$TARGET_GSDEVTOOLS" "$URL_GSDEVTOOLS"
curl -o "$TARGET_INERTIA" "$URL_INERTIA"
curl -o "$TARGET_MOTIONPATHHELPER" "$URL_MOTIONPATHHELPER"
curl -o "$TARGET_MOTIONPATH" "$URL_MOTIONPATH"
curl -o "$TARGET_MORPHSVG" "$URL_MORPHSVG"
curl -o "$TARGET_OBSERVER" "$URL_OBSERVER"
curl -o "$TARGET_PHYSICS2D" "$URL_PHYSICS2D"
curl -o "$TARGET_PHYSICSPROPS" "$URL_PHYSICSPROPS"
curl -o "$TARGET_PIXI" "$URL_PIXI"
curl -o "$TARGET_SCRAMBLETEXT" "$URL_SCRAMBLETEXT"
curl -o "$TARGET_SCROLLTRIGGER" "$URL_SCROLLTRIGGER"
curl -o "$TARGET_SCROLLSMOOTHER" "$URL_SCROLLSMOOTHER"
curl -o "$TARGET_SCROLLTO" "$URL_SCROLLTO"
curl -o "$TARGET_SPLITTEXT" "$URL_SPLITTEXT"
curl -o "$TARGET_TEXTP" "$URL_TEXTP"
curl -o "$TARGET_EASEPACK" "$URL_EASEPACK"
curl -o "$TARGET_CUSTOMEASE" "$URL_CUSTOMEASE"
curl -o "$TARGET_CUSTOMBOUNCE" "$URL_CUSTOMBOUNCE"
curl -o "$TARGET_CUSTOMWIGGLE" "$URL_CUSTOMWIGGLE"
###curl -o "$TARGET_LICENSE" "$URL_LICENSE"

echo
echo "==================================="
echo "Finished downloading GSAP files"
echo
